#!/usr/bin/env bash
# gen-api-probe.sh — write a probe program that includes every [lib] module and
# calls EVERY public fn listed in docs/development/api-surface-1.0.snapshot
# (zero arguments at the recorded arity), behind a guard that is never true at
# run time. It exists to be COMPILED, not run.
#
# Why: cyrius reports an undefined function only when its calling fn is
# reachable. src/main.cyr reaches just the core modules, so the agnos build of
# it never compiled the agnos arms of journald / netns / bootloader / update /
# fuse at all, and the tests reach only what they call. Building this probe
# with --agnos makes every public fn — and so every agnos arm — reachable.
#
# Usage: scripts/gen-api-probe.sh > build/api_probe.cyr
#        CYRIUS_DCE=1 cyrius build --agnos build/api_probe.cyr build/api_probe
# The stdlib resolves from cyrius.cyml [deps] stdlib; only src/ is included.
set -euo pipefail
export LC_ALL=C

SNAPSHOT="docs/development/api-surface-1.0.snapshot"
[ -f "$SNAPSHOT" ] || { echo "gen-api-probe: $SNAPSHOT missing" >&2; exit 1; }

# [lib] modules, in declared order (the order the bundle concatenates them).
modules=$(awk '
    /^\[lib\]/ { inlib = 1; next }
    /^\[/      { inlib = 0 }
    inlib && /"src\/[a-z_]+\.cyr"/ { match($0, /"src\/[a-z_]+\.cyr"/); print substr($0, RSTART + 1, RLENGTH - 2) }
' cyrius.cyml)
[ -n "$modules" ] || { echo "gen-api-probe: no [lib] modules in cyrius.cyml" >&2; exit 1; }

echo "# Generated by scripts/gen-api-probe.sh — do not edit. Compile-only probe."
for m in $modules; do echo "include \"$m\""; done
echo ""
echo "fn main(): i64 {"
echo "    alloc_init();"
echo "    if (sys_getpid() == 0 - 7) {"
awk -F'::' '
    NF == 2 {
        split($2, a, "/"); fn = a[1]; n = a[2] + 0
        args = ""
        for (i = 0; i < n; i++) args = args (i ? ", " : "") "0"
        printf "        %s(%s);\n", fn, args
        count++
    }
    END { if (count == 0) exit 1 }
' "$SNAPSHOT" || { echo "gen-api-probe: no fns parsed from $SNAPSHOT" >&2; exit 1; }
echo "    }"
echo "    return 0;"
echo "}"
echo "var r = main();"
echo "sys_exit(r);"
